export const SEED_PROFILES = [
  {
    id: 'seed-1',
    name: 'Aryan',
    age: 28,
    gender: 'Male',
    city: 'Delhi',
    area: 'South Delhi',
    sport: '["hyrox"]',
    level: 'intermediate',
    bio: 'Engineer by day, HYROX-obsessed by night. Looking for a training partner who shows up every session.',
    photo_url: null,
    target_race: 'Masters Union HYROX Delhi',
    hyrox_category: 'open',
    hyrox_strong: '["SkiErg","Rowing","Farmers Carry"]',
    hyrox_weak: '["Sled Push","Wall Balls"]',
    hyrox_5k_time: '26:30',
    race_goal: 'Competing for time',
    training_days: '5-6 days',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Same as me',
    partner_gender_pref: 'No preference',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 42,
  },
  {
    id: 'seed-2',
    name: 'Ayesha',
    age: 29,
    gender: 'Female',
    city: 'Bangalore',
    area: 'Koramangala',
    sport: '["marathon"]',
    level: 'advanced',
    bio: 'Sub-3:30 goal for Mumbai 2027. 100km weeks. Early morning runner. Looking for a long-run partner.',
    photo_url: null,
    target_race: 'Tata Mumbai Marathon',
    marathon_distance: 'Full Marathon',
    marathon_pace: '4:45',
    marathon_weekly_km: '80km+',
    marathon_goal: 'Hit a target time',
    race_goal: 'Hit a target time',
    training_days: '6-7 days',
    partner_goal: 'Long run partner',
    partner_level_pref: 'Same as me',
    partner_gender_pref: 'Women only',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 67,
  },
  {
    id: 'seed-3',
    name: 'Vikram',
    age: 33,
    gender: 'Male',
    city: 'Mumbai',
    area: 'Bandra',
    sport: '["hyrox","marathon"]',
    level: 'advanced',
    bio: 'HYROX doubles racer + full marathon runner. Train hard, race smart. Looking for someone who does both.',
    photo_url: null,
    target_race: 'TCS World 10K',
    hyrox_category: 'doubles',
    hyrox_strong: '["Sled Push","Farmers Carry","Sandbag Lunges"]',
    hyrox_weak: '["SkiErg","Wall Balls"]',
    hyrox_5k_time: '24:00',
    race_goal: 'Competing for time',
    marathon_distance: 'Full Marathon',
    marathon_pace: '5:00',
    marathon_weekly_km: '60-80km',
    marathon_goal: 'Beat my PB',
    training_days: '5-6 days',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Same as me',
    partner_gender_pref: 'No preference',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 54,
  },
];
