export const SEED_PROFILES = [
  {
    id: 'seed-1',
    name: 'Arjun M.',
    age: 28,
    gender: 'Male',
    city: 'Delhi',
    area: 'South Delhi',
    sport: '["hyrox"]',
    level: 'intermediate',
    bio: 'Engineer by day, Hyrox-obsessed by night.',
    photo_url: null,
    target_race: 'Masters Union HYROX Delhi',
    hyrox_category: 'open',
    hyrox_strong: '["SkiErg","Rowing"]',
    hyrox_weak: '["Sled Push","Wall Balls"]',
    hyrox_5k_time: '26:30',
    training_days: '5-6 days',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'No preference',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 42,
  },
  {
    id: 'seed-2',
    name: 'Priya K.',
    age: 31,
    gender: 'Female',
    city: 'Mumbai',
    area: 'Bandra',
    sport: '["marathon"]',
    level: 'advanced',
    bio: 'Chasing sub-4 at Mumbai Marathon. 80km weeks.',
    photo_url: null,
    target_race: 'Tata Mumbai Marathon',
    marathon_distance: 'Full Marathon',
    marathon_pace: '5:20',
    marathon_weekly_km: '80km+',
    marathon_goal: 'Beat my PB',
    training_days: '5-6 days',
    partner_goal: 'Full training partner',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'No preference',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 89,
  },
  {
    id: 'seed-3',
    name: 'Rahul S.',
    age: 24,
    gender: 'Male',
    city: 'Delhi',
    area: 'Noida',
    sport: '["hyrox"]',
    level: 'rookie',
    bio: 'First Hyrox in July. Looking for a training crew.',
    photo_url: null,
    target_race: 'Masters Union HYROX Delhi',
    hyrox_category: 'open',
    hyrox_strong: '["Wall Balls"]',
    hyrox_weak: '["SkiErg","Sled Pull"]',
    hyrox_5k_time: '32:00',
    training_days: '3-4 days',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Challenge me',
    partner_gender_pref: 'No preference',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 15,
  },
  {
    id: 'seed-4',
    name: 'Ayesha N.',
    age: 29,
    gender: 'Female',
    city: 'Bangalore',
    area: 'Koramangala',
    sport: '["marathon"]',
    level: 'advanced',
    bio: 'Sub-3:30 goal. 100km weeks. Early morning runner.',
    photo_url: null,
    target_race: 'TCS World 10K',
    marathon_distance: 'Full Marathon',
    marathon_pace: '4:45',
    marathon_weekly_km: '80km+',
    marathon_goal: 'Compete and place',
    training_days: '5-6 days',
    partner_goal: 'Full training partner',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'Women only',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 67,
  },
  {
    id: 'seed-5',
    name: 'Vikram T.',
    age: 33,
    gender: 'Male',
    city: 'Mumbai',
    area: 'Powai',
    sport: '["hyrox","marathon"]',
    level: 'advanced',
    bio: 'HYROX doubles + full marathon. Train hard, race smart.',
    photo_url: null,
    target_race: 'HYROX Mumbai',
    hyrox_category: 'doubles',
    hyrox_strong: '["Sled Push","Farmers Carry"]',
    hyrox_weak: '["SkiErg"]',
    hyrox_5k_time: '24:00',
    marathon_distance: 'Full Marathon',
    marathon_pace: '5:00',
    marathon_weekly_km: '60-80km',
    training_days: '5-6 days',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'No preference',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 54,
  },
  {
    id: 'seed-6',
    name: 'Sneha I.',
    age: 27,
    gender: 'Female',
    city: 'Mumbai',
    area: 'Andheri',
    sport: '["hyrox"]',
    level: 'elite',
    bio: 'Pro division athlete. 7 days a week. No shortcuts.',
    photo_url: null,
    target_race: 'HYROX Bengaluru',
    hyrox_category: 'pro',
    hyrox_strong: '["SkiErg","Sled Push","Sled Pull","Rowing","Wall Balls"]',
    hyrox_weak: '[]',
    hyrox_5k_time: '20:00',
    training_days: 'Every day',
    partner_goal: 'Train regularly',
    partner_level_pref: 'Same level',
    partner_gender_pref: 'No preference',
    email_verified: true,
    flagged: false,
    last_active: new Date().toISOString(),
    profile_views: 123,
  },
];
